/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/video/Camera.vue')['default']
    Content: typeof import('./src/components/layout-main/Content.vue')['default']
    DynamicIcon: typeof import('./src/components/dynamicIcon/DynamicIcon.vue')['default']
    Footer: typeof import('./src/components/layout-main/Footer.vue')['default']
    Head: typeof import('./src/components/layout-main/Head.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/three/Test.vue')['default']
    ThreeOne: typeof import('./src/components/three/Three-One.vue')['default']
    ThreeThree: typeof import('./src/components/three/Three-three.vue')['default']
    ThreeTwo: typeof import('./src/components/three/Three-Two.vue')['default']
    UploadImage: typeof import('./src/components/upload/UploadImage.vue')['default']
    UploadVideo: typeof import('./src/components/upload/UploadVideo.vue')['default']
  }
}
